import requests
import json
import random
from shapely.geometry import Point

# Calling the OpenStreetMap API and using json library to get the response
def driving_time(lon_1, lat_1, lon_2, lat_2):
    """
    Parameters are two places longitude and latitude

    Returns the driving distance from 1 to 2 in seconds.
    """
    r = requests.get(
        f"""http://router.project-osrm.org/route/v1/car/{lat_1},{lon_1};{lat_2},{lon_2}?overview=false"""
    )

    # routes can have more than one alternative route but we choose the first one which is the better one
    routes = json.loads(r.content)["routes"][0]

    return routes["duration"]  # returns the driving duration in seconds


# print(driving_time(38.808809, -111.339107, 39.196708, -112.081877))


def coordinate_generator(area):
    """
    Generates a random location coordinates bettwen the given geographical limits of the area
    Area is a polygon generated by chosen locations
    """
    westernmost, southernmost, easternmost, northernmost = area.bounds
    random_point = Point(
        [
            round(random.uniform(westernmost, easternmost), 6),
            round(random.uniform(southernmost, northernmost), 6),
        ]
    )
    if random_point.within(area):
        # print(random_point)
        return {"lat": random_point.x, "lon": random_point.y}
    else:
        return coordinate_generator(area)
